# Generated by Django 5.0.1 on 2024-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Названее'),
        ),
    ]
